README.md

Was most likely an oversight of copy-pasting but the Scoop link actually redirects to the Chocolatey homepage.

Fix README link on scoop

---

LICENSE.txt

This is more of a nitpick, but here it goes:
1. GitHub has a system to automatically determine the license of a repository. However, currently it cannot actually retrieve it because it doesn't match anything in their database:
*On the top left right, it says 'View License' because it cannot be identified as MIT...*
2. This PR also splits the license across multiple lines. Nobody wants to read the license like this:

Rearrange license body

---

README.md
src/gsudo.Tests/ArgumentParsingTests.cs
src/gsudo/Commands/HelpCommand.cs
src/gsudo/Commands/RunCommand.cs
src/gsudo/Commands/ServiceCommand.cs
src/gsudo/Commands/SystemServiceCommand.cs
src/gsudo/GlobalSettings.cs
src/gsudo/Helpers/ArgumentsHelper.cs
src/gsudo/Helpers/ProcessFactory.cs
src/gsudo/Helpers/ShellHelper.cs
src/gsudo/Helpers/TerminalHelper.cs
src/gsudo/Native/ProcessApi.cs
src/gsudo/Native/TokensApi.cs
src/gsudo/ProcessHosts/AttachedConsoleHost.cs
src/gsudo/ProcessHosts/IProcessHost.cs
src/gsudo/ProcessHosts/NewWindowProcessHost.cs
src/gsudo/ProcessHosts/PipedProcessHost.cs
src/gsudo/ProcessHosts/VTProcessHost.cs
src/gsudo/ProcessRenderers/AttachedConsoleRenderer.cs
src/gsudo/ProcessRenderers/IProcessRenderer.cs
src/gsudo/ProcessRenderers/PipedClientRenderer.cs
src/gsudo/ProcessRenderers/VTClientRenderer.cs
src/gsudo/Program.cs
src/gsudo/Rpc/IRpcClient.cs
src/gsudo/Rpc/NamedPipeServer.cs

New Features
- Added `-s / --system` parameter to run as Local System Account.
Fixes:
- Fixed PowerShell arguments when calling `gsudo` with or without arguments
Contemplates PSCore 6.0.0 to 6.2.3 bug when installed as a global tool.

Release 0.6

---

src/gsudo/Rpc/NamedPipeServer.cs

Use well-known SID for "NT Authority\Network" to work in all locales.

---

build/Build.bat
build/Chocolatey/gsudo/tools/chocolateyinstall.ps1
build/Chocolatey/gsudo/tools/chocolateyuninstall.ps1
src/gsudo/Commands/BangBangCommand.cs
src/gsudo/Helpers/ConsoleHelper.cs
src/gsudo/Native/ConsoleApi.cs
src/gsudo/Settings.cs
src/gsudo/gsudo.csproj

Fixes:
- Fix Unhandled Exception when pressing CTRL+C after 4 minutes runtime  (Ctrl-C Handler delegate was garbage collected). (#53)
- Fix Choco package issue when the user is not admin and installs as another user (#50)
- Fix gsudo red ´#´ prompt breaking console color scheme on some scenarios (#51)
- Fix `gsudo !prefix` now case insensitive.

Release v0.7.2 

---

src/gsudo/Helpers/ArgumentsHelper.cs
src/gsudo/Helpers/ShellHelper.cs

Take command usually sets COMSPEC, but often (as in my case)
COMSPEC still points to cmd.exe for obscure batch file compatibility.

Support Take Command (regardless of COMSPEC)

---

docs/docs/usage/powershell.md
src/gsudo.Wrappers/Invoke-gsudo.ps1
src/gsudo.Wrappers/gsudoModule.psd1
src/gsudo.Wrappers/gsudoModule.psm1
src/gsudo/Commands/ConfigCommand.cs

- `gsudo config {configKey}` now parseable
- Invoke-gsudo now uses `gsudo config PowershellLoadProfile`

Fix (technical debt): Unify `gsudo config PowerShellLoadProfile` and `$gsudoLoadProfile` into the first one.

---

src/gsudo.Tests/CommandLineParserTests.cs
src/gsudo/AppSettings/RegistrySetting.cs
src/gsudo/AppSettings/Settings.cs
src/gsudo/AppSettings/Window.cs
src/gsudo/Commands/ConfigCommand.cs
src/gsudo/Commands/HelpCommand.cs
src/gsudo/Commands/RunCommand.cs
src/gsudo/Commands/ServiceCommand.cs
src/gsudo/Helpers/ArgumentsHelper.cs
src/gsudo/Helpers/CommandLineParser.cs
src/gsudo/Helpers/CommandToRunAdapter.cs
src/gsudo/Helpers/ExtensionMethods.cs
src/gsudo/Helpers/ShellHelper.cs
src/gsudo/InputParameters.cs

- Added setting `gsudo config NewWindow.Force` to force every elevation in new window. Same as using `-n` every time.
- Added `--NoExit`: Keep elevated shell open after running {command}.
- Added `--NoClose`: When in new console, ask for keypress before closing the console.
- Added setting `gsudo config NewWindow.CloseBehaviour`: `OsDefault`, `KeepShellOpen` (--NoExit), PressKeyToClose(--NoClose)
- Config syntax more relaxed now:
```
gsudo.exe config loglevel debug
gsudo.exe config loglevel=debug
gsudo.exe config loglevel="debug"
gsudo.exe config loglevel =  debug
```

Feature: Force NewWindow + New window --NoClose & Shell --NoExit

---

.github/workflows/release.yml
build/04-release-GitHub.ps1
src/gsudo.Installer.sln
src/gsudo.Installer/Constants.Template.wxi
src/gsudo.Installer/Product.wxs
src/gsudo.Installer/gsudomsi.wixproj
src/gsudo.Installer/packages.config

Fixes #243
With this, you probably no longer need "wixtoolset", although you will probably want to install the [HeatWave for VS2022](https://marketplace.visualstudio.com/items?itemName=FireGiant.FireGiantHeatWaveDev17) extension into your Visual Studio.
Each package will prevent itself from installing on any platform except that which it was intended for. Any of them will remove previous versions since they all share the same `UpgradeCode`.
I couldn't get the build powerscripts to run as intended, but I did manage to get everything built in order to convert and build the installers.
This leaves in place all of your existing custom actions, etc. which should continue to run as before. It also leaves in place your "install versioned and [re]point "current" (which is what is placed into the …

Convert to Wix v4, divide installers into three packages, and update build script

---

src/gsudo.Wrappers/gsudo

In WSL, when gsudo is not in `PATH` env var, the bash wrapper script cannot run because `gsudo.exe` is called without a path.
Assuming the `gsudo` bash script will always be in the same directory as `gsudo.exe`, we can use `$( dirname -- "$0" )`. See https://stackoverflow.com/a/59916/84091

fix call to bash wrapper `gsudo` without PATH env var set

---

src/gsudo/Helpers/CommandToRunAdapter.cs

When network path contains spaces (e.g. \\vmware-host\Shared Folders\), the net use command fails to execute.

Bugfix: Add quotes around network path

---

.github/workflows/release.yml
src/gsudo.Wrappers/gsudoModule.psd1
src/gsudo.Wrappers/gsudoModule.psm1
src/gsudo/Helpers/CommandToRunAdapter.cs

- Added Auto-Complete for `gsudo` (#233 #258)
- Added Test-IsProcessElevated function, returns true if elevated.
- Added Test-IsAdminMember function, returns true if user is Local admin
- Added gsudoPrompt function to add a red # to the prompt if user is admin. Requires user to call: `Set-Alias prompt gsudoPrompt` to activate.
- Improved `Get-Help gsudo`
- Fixed quoted issue when the first and last argument has arguments.

v2.1.0 New PowerShell features + Auto-complete

---

README.md
build/01-build.ps1
build/Chocolatey/gsudo/tools/chocolateyinstall.ps1
docs/docs/usage/powershell.md
installgsudo.ps1
src/gsudo.Installer/Product.wxs
src/gsudo/Commands/BangBangCommand.cs

Improvements to gsudo PowerShell Module:
-  The Wix (msi) installer will deploy PowerShell gsudoModule to '%ProgramFiles%\PowerShell\Modules\gsudoModule\', so `Import-Module gsudoModule` does not requires an absolute path anymore
-  The `Chocolatey` installer also will deploy PowerShell gsudoModule to '%ProgramFiles%\PowerShell\Modules\gsudoModule\'
-  The module version number is now properly updated with the build version.
- Updated docs to suggest `Import-Module gsudoModule` instead of the absolute path.

PowerShell Module Improvements

---

docs/docs/tips/script-self-elevation.md
sample-scripts/many-elevations-using-gsudo-cache.cmd
sample-scripts/many-elevations-using-gsudo-cache.ps1
sample-scripts/readme.md
sample-scripts/self-elevate-one-liner.cmd
sample-scripts/self-elevate-without-gsudo.cmd
sample-scripts/self-elevate.cmd
sample-scripts/self-elevate.ps1
sample-scripts/silent-elevation-one-liner.cmd
sample-scripts/silent-elevation.cmd
src/gsudo.Wrappers/gsudoModule.psm1
src/gsudo/Commands/CacheCommand.cs
src/gsudo/Commands/HelpCommand.cs
src/gsudo/Commands/StatusCommand.cs
src/gsudo/Helpers/CommandLineParser.cs

- `gsudo status {key}` returns exit code for booleans: 0(success) for true, 1(fail) for false
- Added sample usage scripts and docs
- Fixed issue on Cache ON not propagating loglevel or duration if cache was already active

Improve gsudo scripting scenarios

---

src/gsudo/Commands/RunCommand.cs
src/gsudo/Commands/ServiceCommand.cs
src/gsudo/Helpers/ConsoleHelper.cs
src/gsudo/Helpers/ServiceHelper.cs
src/gsudo/ProcessRenderers/TokenSwitchRenderer.cs
src/gsudo/Rpc/Connection.cs
src/gsudo/Rpc/IRpcClient.cs
src/gsudo/Rpc/NamedPipeClient.cs
src/gsudo/Rpc/NamedPipeServer.cs

Fix for "Error: Unable to connect to the elevated service." and "NullReferenceException"
Hopefully fixes #291: Issue: gsudo --ti doesn't work like we've expected. gsudo -s and other commands works well but gsudo --ti (TrustedInstaller) doesn't work

Fix "Error: Unable to connect to the elevated service"/"NullReferenceException"

---

README.md

* #296
Just adds some more detail to the manual install technique.

docs: improve README.md manual installation technique, fixes #296

---

docs/src/components/HomepageFeatures/index.js

Include Nushell on homepage given support following #154.
---
I’m unsure on order, so I just put Nushell where we were missing a space already. Feel free to request an order change.
I went looking for Nushell support after not seeing it on the homepage.

Docs: Include Nushell on homepage

---

src/gsudo/Helpers/CommandLineParser.cs
src/gsudo/Helpers/CommandToRunAdapter.cs

Fix `Error: Invalid option: -noninteractive` using `gsudo {command}` on Visual Studio code

---

src/gsudo.Wrappers.Tests/Invoke-gsudo.Tests.ps1
src/gsudo.Wrappers/gsudo
src/gsudo/AppSettings/Settings.cs
src/gsudo/Commands/RunCommand.cs
src/gsudo/Commands/ServiceCommand.cs
src/gsudo/Commands/StatusCommand.cs
src/gsudo/Helpers/ProcessFactory.cs
src/gsudo/Helpers/ServiceHelper.cs
src/gsudo/Native/NativeMethods.cs
src/gsudo/Native/ProcessApi.cs
src/gsudo/Native/SafeTokenHandle.cs
src/gsudo/Native/TokensApi.cs
src/gsudo/ProcessRenderers/TokenSwitchRenderer.cs
src/gsudo/Rpc/NamedPipeNameFactory.cs
src/gsudo/Tokens/PrivilegeManager.cs
src/gsudo/Tokens/TokenSwitcher.cs
src/gsudo/gsudo.csproj

* Restricted process and thread handles in TokenSwitchMode.
* Restricted ACL of the elevated process to High Integrity.
* Fixed issue elevating to MediumPlus integrity level
* Add workaround for vim and nano. Fixes #248 #302
* Fix error when user configures CacheDuration > 24 days. Fixes #318
* Fix Issue when multiple simultaneous gsudo versions throw `Unauthorized. (Different gsudo.exe?)`. Fixes #300
* Fix PowerShell Unit Tests for Pwsh v7.4

Release v2.4.3

---

src/gsudo.Wrappers/gsudoModule.psm1
src/gsudo/AppSettings/PathPrecedenceSetting.cs
src/gsudo/AppSettings/Settings.cs

Defines a setting to reorder the PATH environment variable to prioritize gsudo's path over Microsoft sudo on System32

New PathPrecedence Setting to reorder the PATH environment variable

---

src/gsudo/AppSettings/PathPrecedenceSetting.cs
src/gsudo/AppSettings/RegistrySetting.cs
src/gsudo/AppSettings/Settings.cs
src/gsudo/Commands/ConfigCommand.cs

This PR includes the following changes:
- Added descriptions to the config settings

[feature/config-descriptions] Added descriptions to the config settings

---

README.md
docs/docs/usage/usage.md
global.json
src/gsudo/AppSettings/PathPrecedenceSetting.cs
src/gsudo/AppSettings/Settings.cs
src/gsudo/Commands/ConfigCommand.cs
src/gsudo/Commands/HelpCommand.cs
src/gsudo/Commands/RunCommand.cs
src/gsudo/ElevationRequest.cs
src/gsudo/Helpers/CommandLineParser.cs
src/gsudo/Helpers/CommandToRunAdapter.cs
src/gsudo/Helpers/ProcessFactory.cs
src/gsudo/Helpers/ServiceHelper.cs
src/gsudo/Helpers/UACWindowFocusHelper.cs
src/gsudo/InputParameters.cs
src/gsudo/Native/FileApi.cs
src/gsudo/ProcessHosts/AttachedConsoleHost.cs
src/gsudo/ProcessHosts/PipedProcessHost.cs
src/gsudo/ProcessHosts/TokenSwitchHost.cs
src/gsudo/ProcessRenderers/TokenSwitchRenderer.cs
src/gsudo/ProcessRenderers/VTClientRenderer.cs
src/gsudo/Program.cs

This PR includes the following changes:
- Included new aliases of existing ones for ms-sudo CLI compatibility (`--preserve-env`, `--new-window`, '--inline').
- Added argument for starting directory: `--chdir {directory}` (or uppercase `-D {directory}`) arguments

Added --chdir and other ms-sudo compatibilities.

---

src/gsudo/Helpers/ConsoleHelper.cs

In my original pull request (https://github.com/gerardog/gsudo/pull/388) adding support for the GSUDO_ASKPASS_NAMED_PIPE environment variable, I made a minor mistake: the named pipe name should *not* include the \\.\pipe\ path prefix.
Here is how to properly test this feature:
Save this to an AskpassNamedPipeServer.ps1 file:
```powershell
param (
[string] $PipeName = "MyNamedPipe",
[string] $Password = "MySecretPassword"
)
$FullPipeName = "\\.\pipe\$PipeName"
$PipeServer = New-Object System.IO.Pipes.NamedPipeServerStream($PipeName, [System.IO.Pipes.PipeDirection]::Out)
Write-Host "Waiting for client to connect to the pipe '$FullPipeName'..."
$PipeServer.WaitForConnection()
$StreamWriter = New-Object System.IO.StreamWriter($PipeServer)
$StreamWriter.WriteLine($Password) …
```

fix askpass named pipe name path prefix
